//
//  ProductSummaryPresenter.swift
//  OPN-Challenge
//
//  Created by A667209 A667209 on 12/5/2567 BE.
//  Copyright (c) 2567 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ProductSummaryPresentationLogic
{
  func presentSomething(response: ProductSummary.Something.Response)
}

class ProductSummaryPresenter: ProductSummaryPresentationLogic
{
  weak var viewController: ProductSummaryDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: ProductSummary.Something.Response)
  {
    let viewModel = ProductSummary.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
